[features]
seeds = false
skip-lint = false
[programs.mainnet]
feature_gate_noop = "2rqZsQBbacRbuAuTSuJ7n49UQT9fzes8RLggFcmB9YuN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"