[features]
seeds = false
skip-lint = false
[programs.mainnet]
feature_gate_noop = "37Yr1mVPdfUuy6oC2yPjWtg8xyyVi33TYYqyNQocsAkT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"
